project_id = "sgarwrreywadxsodnxng"

[functions.create-initial-users]
verify_jwt = false

[functions.send-webhook]
verify_jwt = true

[functions.auto-approve-contents]
verify_jwt = false

[functions.force-reset-all-passwords]
verify_jwt = false

[functions.notify-event]
verify_jwt = false

[functions.test-notification]
verify_jwt = false
