project_id = "sgarwrreywadxsodnxng"

[functions.approval-media-urls]
verify_jwt = false

[functions.archive-contents]
verify_jwt = true

[functions.create-checkout]
verify_jwt = true

[functions.exchange-facebook-token]
verify_jwt = false

[functions.facebook-data-deletion]
verify_jwt = false

[functions.validate-approval-token]
verify_jwt = false

[functions.notify-ip-unblock]
verify_jwt = false

[functions.subscription-enforcement]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.create-billing-portal]
verify_jwt = true

[functions.cleanup-orphaned-accounts]
verify_jwt = false

[functions.daily-report]
verify_jwt = false