project_id = "sgarwrreywadxsodnxng"

[functions.create-initial-users]
verify_jwt = false

[functions.send-webhook]
verify_jwt = false

[functions.auto-approve-contents]
verify_jwt = false

[functions.force-reset-all-passwords]
verify_jwt = false

[functions.notify-event]
verify_jwt = false

[functions.test-notification]
verify_jwt = false

[functions.exchange-facebook-token]
verify_jwt = false

[functions.publish-to-social]
verify_jwt = false

[functions.facebook-data-deletion]
verify_jwt = false
