project_id = "sgarwrreywadxsodnxng"

[functions.exchange-facebook-token]
verify_jwt = false

[functions.facebook-data-deletion]
verify_jwt = false

[functions.validate-approval-token]
verify_jwt = false

[functions.notify-ip-unblock]
verify_jwt = false

[functions.create-billing-portal]
verify_jwt = true